import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { generateClipScript, submitFalJob } from '@/lib/xenttech/clips'

export const dynamic = 'force-dynamic'

function db() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } }
  )
}

export async function POST(req: NextRequest) {
  const body = await req.json() as {
    agent_id:          string
    topic:             string
    tone?:             string
    duration_seconds?: number
    auto_publish?:     boolean
    // Pre-generated by /api/clips/script-only
    hook_selected?:    string
    script?:           string
    video_prompt?:     string
    cta?:              string
    // Brand identity
    brand_colors?:     string[]
    reference_images?: string[]
  }

  const {
    agent_id,
    topic,
    tone             = 'professional',
    duration_seconds = 10,
    auto_publish     = false,
    hook_selected,
    script:           preScript,
    video_prompt:     preVideoPrompt,
    cta:              preCta,
    brand_colors     = [],
    reference_images = [],
  } = body

  if (!agent_id || !topic?.trim()) {
    return NextResponse.json({ error: 'agent_id y topic son requeridos' }, { status: 400 })
  }

  const supabase = db()

  const { data: agent } = await supabase
    .from('xenttech_agents')
    .select('id, name, system_prompt')
    .eq('id', agent_id)
    .maybeSingle()

  if (!agent) return NextResponse.json({ error: 'Agente no encontrado' }, { status: 404 })

  // If no pre-generated script, call Claude now (fast, ~3s)
  let script      = preScript      ?? null
  let videoPrompt = preVideoPrompt ?? null
  let hook        = hook_selected  ?? null
  let cta         = preCta         ?? null

  if (!videoPrompt) {
    try {
      const plan = await generateClipScript(agent, topic, tone, duration_seconds, brand_colors, reference_images)
      videoPrompt = plan.video_prompt
      script      = plan.script
      hook        = plan.hook_options[0] ?? null
      cta         = plan.cta
    } catch (err) {
      return NextResponse.json({ error: `Claude error: ${(err as Error).message}` }, { status: 502 })
    }
  }

  // Submit Fal.ai job (non-blocking, returns request_id immediately)
  let requestId: string | null = null
  let falModel:  string | null = null
  try {
    const referenceImageUrl = reference_images.length > 0 ? reference_images[0] : undefined
    const submitted = await submitFalJob(videoPrompt!, duration_seconds, referenceImageUrl)
    requestId = submitted.request_id
    falModel  = submitted.model
  } catch (err) {
    return NextResponse.json({ error: `Fal.ai submit error: ${(err as Error).message}` }, { status: 502 })
  }

  // Insert clip record with everything we know now
  const { data: clip, error: insertError } = await supabase
    .from('xenttech_clips_ai')
    .insert({
      agent_id,
      topic,
      tone,
      duration_seconds,
      auto_publish,
      status:             'generating',
      script,
      hook,
      cta,
      video_prompt:       videoPrompt,
      brand_colors,
      reference_images,
      generation_task_id: requestId,
      fal_model:          falModel,
    })
    .select()
    .single()

  if (insertError || !clip) {
    return NextResponse.json({ error: insertError?.message ?? 'Insert failed' }, { status: 500 })
  }

  return NextResponse.json({
    clip_id:        clip.id,
    fal_request_id: requestId,
    status:         'generating',
    message:        'Video enviado a Kling. El frontend hará polling cada 10s.',
  })
}
